{{- if .Values.kubeAPI.apiAuth.serviceAccount.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-operator.fullname" . }}-api-auth
  labels:
    {{- include "auth-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "auth-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-auth
  template:
    metadata:
      labels:
        {{- include "auth-operator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api-auth
      annotations:
        {{- if .Values.store.openbao.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.store.openbao.proxy.authMethod.apiAuth.kubernetes.role }}
        vault.hashicorp.com/agent-inject-secret-master: "{{ .Values.store.openbao.kv2MountPath }}/{{ .Values.store.openbao.masterSecretPath }}/master"
        vault.hashicorp.com/template-static-secret-render-interval: "1m"
        {{- if .Values.store.openbao.tls.selfSigned }}
        vault.hashicorp.com/ca-cert: "/vault/tls/{{ .Values.store.openbao.tls.caCertKey }}"
        vault.hashicorp.com/tls-secret: "{{ .Values.store.openbao.tls.secretName }}"
        {{- end }}
        vault.hashicorp.com/log-level: "trace"
        vault.hashicorp.com/agent-inject-template-master: |
          {{`{{- with secret "`}}{{ .Values.store.openbao.kv2MountPath }}{{`/`}}{{ .Values.store.openbao.masterSecretPath }}{{`/master" -}}` }}
          {{`{{ .Data.data | toJSON }}
          {{- end -}}` }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.kubeAPI.apiAuth.serviceAccount.name }}
      securityContext:
        runAsUser: 1001
      containers:
        - name: api-auth
          image: "git.championtourney.com/championtourney/api-auth:{{ .Values.image.apiAuth.tag }}"
          imagePullPolicy: {{ .Values.image.apiAuth.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8080
          env:
            {{- if .Values.store.openbao.enabled }}

            - name: CLIENT_SECRET_FILE
              value: "/vault/secrets/master"

            - name: STORE
              value: "openbao"

            - name: VAULT_TRANSIT_MOUNT_PATH
              value: "{{ .Values.store.openbao.transitMountPath }}"

            - name: VAULT_SIGNING_KEY
              value: "{{ .Values.store.openbao.transitSigningKey }}"

            - name: KUBERNETES_ROLE
              value: "{{ .Values.store.openbao.proxy.authMethod.apiAuth.kubernetes.role }}"

            {{- end}}

            - name: APPLICATION_PORT
              value: "8080"
{{- end }}
